### PR TITLE
added basic async mapper support

### PR DESCRIPTION
**Pull request by jtruelove**

### CODE REVIEW

**Comment by adrianluisgonzalez** [comment]
Hi,

I've been thinking about how best to add mapping support.  I am leaning towards changing CassandraSession to extend the driver's Session which would allow you to use the Mapping manager directly and the callbacks will correctly run on the vert.x event loop.

When I started the vertx-cassandra project, Session was a class which was why I created my own interface.  This is a major breaking change, but it is still a SNAPSHOT build of 2.0.0 so I think it is worth doing sooner rather than later.

Thoughts?

**Comment by jtruelove** [comment]
Yeah that sounds a lot cleaner. This was more of a get it working based on the current structuring of the project sort of patch. Being able to user the mapping manager directly and just have the session do the right thing and execute on the vert.x event loop would be preferable.

**Comment by adrianluisgonzalez** [comment]
I've pushed a feature branch:
https://github.com/englishtown/vertx-cassandra/tree/feature/extend-session

The `com.englishtown.vertx.cassandra.CassandraSession` now extends `com.datastax.driver.core.Session`.  I've also added a `com.englishtown.vertx.cassandra.FutureUtils` helper to run `FutureCallback<T>` on the vert.x context.

This means you can now create the MappingManager with the `CassandraSession`:

```java

String userId = "123";
Vertx vertx = getVertx();
CassandraSession session = getSession();

// Create mapping manager using the com.englishtown.vertx.cassandra.CassandraSession
MappingManager mappingManager = new MappingManager(session);
Mapper<User> mapper = mappingManager.mapper(User.class);

// Callback for when User is returned
FutureCallback<User> callback = new FutureCallback<User>() {
    @Override
    public void onSuccess(User user) {
    }

    @Override
    public void onFailure(Throwable t) {
    }
};

// Add callback to be run on the vert.x context
FutureUtils.addCallback(mapper.getAsync(userId), callback, vertx);

```


What do you think?

**Comment by jtruelove** [comment]
This is the pattern I'm more or less using in my own code right now and one of the reasons I needed the underlying session object exposed a bit back. One thing that would be nice to get around is having to pass that vertx object into the utility function. I get around that by initializing a static var at startup obviously not ideal. I wish there was a way to just grab a ref to the loop when you needed it vs saving it off.

**Comment by adrianluisgonzalez** [comment]
I figured that was why you wanted the Session exposed once I started looking at mapping.

Rather than adding the mapping functionality to the CassandraSession, I would rather a separate module vertx-cassandra-mapping similar to what datastax have done with their driver cassandra-driver-core and cassandra-driver-mapping.  You could extend MappingManager and Mapper to support passing FutureCallbacks which would take care of running on the vert.x context.

**Comment by jtruelove** [comment]
Yeah that seems reasonable to me.

**Comment by adrianluisgonzalez** [comment]
I've added vertx-cassandra-mapping.  Take a look and let me know if you have any comments:

https://github.com/englishtown/vertx-cassandra/tree/feature/mapping

**Comment by mikaelkaron** [comment]
:+1:

**Comment by jtruelove** [comment]
Looks good to me, updating the docs on some examples of usage would be
great as well.

**Comment by adrianluisgonzalez** [comment]
Added some documentation with examples and merged:
https://github.com/englishtown/vertx-cassandra/tree/develop/vertx-cassandra-mapping

**Pull request closed without merging**
